set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports rst_n]

set_property PACKAGE_PIN C19 [get_ports led0_en]
set_property PACKAGE_PIN E19 [get_ports led1_en]
set_property PACKAGE_PIN D19 [get_ports led2_en]
set_property PACKAGE_PIN F18 [get_ports led3_en]
set_property PACKAGE_PIN E18 [get_ports led4_en]
set_property PACKAGE_PIN B20 [get_ports led5_en]
set_property PACKAGE_PIN A20 [get_ports led6_en]
set_property PACKAGE_PIN A18 [get_ports led7_en]

set_property PACKAGE_PIN F15 [get_ports led_ca]
set_property PACKAGE_PIN F13 [get_ports led_cb]
set_property PACKAGE_PIN F14 [get_ports led_cc]
set_property PACKAGE_PIN F16 [get_ports led_cd]
set_property PACKAGE_PIN E17 [get_ports led_ce]
set_property PACKAGE_PIN C14 [get_ports led_cf]
set_property PACKAGE_PIN C15 [get_ports led_cg]
set_property PACKAGE_PIN E13 [get_ports led_dp]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports led0_en]
set_property IOSTANDARD LVCMOS33 [get_ports led1_en]
set_property IOSTANDARD LVCMOS33 [get_ports led2_en]
set_property IOSTANDARD LVCMOS33 [get_ports led3_en]
set_property IOSTANDARD LVCMOS33 [get_ports led4_en]
set_property IOSTANDARD LVCMOS33 [get_ports led5_en]
set_property IOSTANDARD LVCMOS33 [get_ports led6_en]
set_property IOSTANDARD LVCMOS33 [get_ports led7_en]

set_property IOSTANDARD LVCMOS33 [get_ports led_ca]
set_property IOSTANDARD LVCMOS33 [get_ports led_cb]
set_property IOSTANDARD LVCMOS33 [get_ports led_cc]
set_property IOSTANDARD LVCMOS33 [get_ports led_cd]
set_property IOSTANDARD LVCMOS33 [get_ports led_ce]
set_property IOSTANDARD LVCMOS33 [get_ports led_cf]
set_property IOSTANDARD LVCMOS33 [get_ports led_cg]
set_property IOSTANDARD LVCMOS33 [get_ports led_dp]

