# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/tjx_riscv_plus_v2_2021_07_23/mini-rv-1_-design/ex3/lab3/lab3.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/tjx_riscv_plus_v2_2021_07_23/mini-rv-1_-design/ex3/lab3/lab3.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/tjx_riscv_plus_v2_2021_07_23/mini-rv-1_-design/ex3/lab3/lab3.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/tjx_riscv_plus_v2_2021_07_23/mini-rv-1_-design/ex3/lab3/lab3.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
